name: glow_bottom_app_bar
description: Simple Bottom App Bar with Glowing transition effect to provide a beautiful effect for navigation
version: 1.3.0
homepage: https://github.com/yashas-hm/glow_bottom_app_bar

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: