name: glow_bottom_app_bar
description: "Bottom App Bar with Glowing transition"
version: 1.0.0
homepage: ''

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
